version: '3.5'
services:
  magento_php:
    container_name: magento_php
    build: .docker/php
    working_dir: /application
    volumes:
      - '.:/application'
      - './.docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    depends_on:
      - magento_redis
      - magento_mysql
      - magento_rabbitmq
      - magento_elasticsearch
      - magento_mailhog

  magento_mysql:
    container_name: magento_mysql
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=magento
    ports:
      - '3306:3306'

  magento_nginx:
    container_name: magento_nginx
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - magento_php

  magento_redis:
    container_name: magento_redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  magento_elasticsearch:
    image: blacktop/elasticsearch:7.16
    container_name: magento_elasticsearch
    environment:
        discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  magento_mailhog:
    container_name: magento_mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '8025:8025'

  magento_rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: magento_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672

  magento_phpmyadmin:
    container_name: magento_phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
